export const TEST_DATA = [
  {
    id: 1,
    first_name: "Santino",
    last_name: "Grimes",
    gender: "male",
    bio: "botany fan, founder 🙀",
    score: 59,
    location: { city: "Bobbiestad", country: "American Samoa" },
    dob: "15/11/2005",
    photos: [
      {
        id: 1,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/534.jpg",
      },
      { id: 2, path: "https://avatars.githubusercontent.com/u/85979379" },
      { id: 3, path: "https://avatars.githubusercontent.com/u/54569220" },
      { id: 4, path: "https://avatars.githubusercontent.com/u/40694988" },
      {
        id: 5,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/411.jpg",
      },
    ],
    interests: [
      { id: 1, name: "olive" },
      { id: 2, name: "orange" },
      { id: 3, name: "purple" },
    ],
    created_at: "2024-03-08T01:49:05.715Z",
  },
  {
    id: 2,
    first_name: "Buck",
    last_name: "MacGyver-Bradtke",
    gender: "female",
    bio: "spoon lover, nerd 🍑",
    score: 2,
    location: { city: "Schaeferview", country: "Zambia" },
    dob: "18/06/1988",
    photos: [
      { id: 1, path: "https://avatars.githubusercontent.com/u/70012786" },
      {
        id: 2,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/550.jpg",
      },
      {
        id: 3,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/551.jpg",
      },
      {
        id: 4,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/774.jpg",
      },
      {
        id: 5,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1243.jpg",
      },
    ],
    interests: [
      { id: 1, name: "turquoise" },
      { id: 2, name: "orchid" },
      { id: 3, name: "plum" },
    ],
    created_at: "2024-03-07T14:55:38.537Z",
  },
  {
    id: 3,
    first_name: "Christine",
    last_name: "Tromp",
    gender: "female",
    bio: "holiday devotee, parent",
    score: 4,
    location: { city: "Rheaside", country: "Honduras" },
    dob: "01/10/1992",
    photos: [
      { id: 1, path: "https://avatars.githubusercontent.com/u/88571812" },
      { id: 2, path: "https://avatars.githubusercontent.com/u/69642628" },
      {
        id: 3,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/267.jpg",
      },
      {
        id: 4,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/36.jpg",
      },
      {
        id: 5,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1011.jpg",
      },
    ],
    interests: [
      { id: 1, name: "tan" },
      { id: 2, name: "indigo" },
      { id: 3, name: "sky blue" },
    ],
    created_at: "2024-03-08T03:36:24.833Z",
  },
  {
    id: 4,
    first_name: "Destin",
    last_name: "Hilpert",
    gender: "male",
    bio: "burro lover",
    score: 93,
    location: { city: "Clifton", country: "Bonaire, Sint Eustatius and Saba" },
    dob: "23/05/2002",
    photos: [
      { id: 1, path: "https://avatars.githubusercontent.com/u/27718778" },
      { id: 2, path: "https://avatars.githubusercontent.com/u/93533753" },
      {
        id: 3,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/377.jpg",
      },
      { id: 4, path: "https://avatars.githubusercontent.com/u/12347591" },
      {
        id: 5,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1150.jpg",
      },
    ],
    interests: [
      { id: 1, name: "lime" },
      { id: 2, name: "tan" },
      { id: 3, name: "azure" },
    ],
    created_at: "2024-03-07T13:01:52.781Z",
  },
  {
    id: 5,
    first_name: "Maci",
    last_name: "Graham",
    gender: "male",
    bio: "dreamer",
    score: 54,
    location: { city: "Adamsmouth", country: "American Samoa" },
    dob: "26/06/1993",
    photos: [
      { id: 1, path: "https://avatars.githubusercontent.com/u/33670028" },
      { id: 2, path: "https://avatars.githubusercontent.com/u/62554264" },
      { id: 3, path: "https://avatars.githubusercontent.com/u/87207330" },
      { id: 4, path: "https://avatars.githubusercontent.com/u/23766063" },
      {
        id: 5,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/693.jpg",
      },
    ],
    interests: [
      { id: 1, name: "silver" },
      { id: 2, name: "white" },
      { id: 3, name: "violet" },
    ],
    created_at: "2024-03-07T21:04:14.563Z",
  },
  {
    id: 6,
    first_name: "Evelyn",
    last_name: "Friesen",
    gender: "male",
    bio: "correspondent supporter, entrepreneur",
    score: 59,
    location: { city: "North Fausto", country: "Tokelau" },
    dob: "01/02/1984",
    photos: [
      { id: 1, path: "https://avatars.githubusercontent.com/u/48973303" },
      { id: 2, path: "https://avatars.githubusercontent.com/u/36792416" },
      {
        id: 3,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/995.jpg",
      },
      { id: 4, path: "https://avatars.githubusercontent.com/u/5175401" },
      {
        id: 5,
        path: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/296.jpg",
      },
    ],
    interests: [
      { id: 1, name: "indigo" },
      { id: 2, name: "salmon" },
      { id: 3, name: "teal" },
    ],
    created_at: "2024-03-07T20:59:07.689Z",
  },
];